[alembic]
script_location = alembic
prepend_sys_path = src
version_path_separator = os
revision_environment = true
sqlalchemy.url =

# Template used when generating new migrations with --template
# file_template = %%(rev)s_%%(slug)s

# Timezone to use when creating new revision files
# timezone = UTC

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic
migrate = INFO

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
