"use client"
import {useCallback,useEffect,useMemo,useState} from "react"
import api from "@/lib/api"
import {useCryptoLivePrices} from "./CryptoLiveTicker"
const money=(n:number)=>n.toLocaleString("en-US",{maximumFractionDigits:2})
type Pos={symbol:string;quantity:number;average_price:number;current_price:number|null;market_value:number;unrealized_pnl:number;realized_pnl:number;stop_price:number|null;take_price:number|null}
type Portfolio={cash_balance:number;market_value:number;equity:number;positions:Pos[]}
type Account={initial_capital:number;cash_balance:number;currency:string}
type Trade={id:number;symbol:string;side:string;quantity:number;price:number;realized_pnl:number|null;reason:string;trade_time:string}
export default function CryptoPaperTerminal({symbol}:{symbol:string}){
 const {prices}=useCryptoLivePrices();const[account,setAccount]=useState<Account|null>(null),[portfolio,setPortfolio]=useState<Portfolio|null>(null),[trades,setTrades]=useState<Trade[]>([]),[price,setPrice]=useState(0),[qty,setQty]=useState("0.01"),[side,setSide]=useState<"BUY"|"SELL">("BUY"),[stop,setStop]=useState(""),[take,setTake]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{const[a,p,t]=await Promise.all([api.get<Account>("/crypto-paper/account"),api.get<Portfolio>("/crypto-paper/portfolio"),api.get<{id:number}[]>("/crypto-paper/trades?limit=20")]);setAccount(a);setPortfolio(p);setTrades(t as Trade[])}catch(e){setMsg(e instanceof Error?e.message:"Crypto paper account unavailable")}},[])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{let alive=true;const tick=async()=>{try{const r=await fetch("https://api.binance.com/api/v3/ticker/price?symbol="+symbol,{cache:"no-store"});const j=await r.json();if(alive)setPrice(Number(j.price))}catch{}};void tick();const id=window.setInterval(tick,15000);return()=>{alive=false;window.clearInterval(id)}},[symbol])
 const livePrice=prices[symbol]?.price||price; const position=portfolio?.positions.find(p=>p.symbol===symbol),q=Math.max(0,Number(qty)||0),cost=q*effectivePrice,equity=portfolio?.equity||account?.initial_capital||100000
 const effectivePrice=livePrice; const unrealized=portfolio?.positions.reduce((s,p)=>s+p.unrealized_pnl,0)||0,exposure=equity?((position?.market_value||0)/equity)*100:0
 const rr=stop&&take&&price>Number(stop)?(Number(take)-price)/(price-Number(stop)):0
 const submit=async()=>{setMsg("");if(!effectivePrice||!q)return setMsg("Enter a valid quantity");if(side==="BUY"&&cost>equity*.25)return setMsg("Risk limit: max 25% of equity per order");setBusy(true);try{await api.post("/crypto-paper/trade?"+new URLSearchParams({symbol,side,quantity:String(q),...(stop?{stop_price:stop}:{}),...(take?{take_price:take}:{})}).toString(),{});setMsg(side+" executed at $"+money(effectivePrice));await load()}catch(e){setMsg(e instanceof Error?e.message:"Trade failed")}finally{setBusy(false)}}
 const squareOff=()=>{if(position){setSide("SELL");setQty(String(position.quantity));setMsg("Full position loaded. Press SELL to confirm.")}}
 return <section className="glass-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="tx-section-title">Crypto Paper Trading</div><p className="text-[11px] text-slate-600">Persistent authenticated paper wallet · USDT · no exchange orders</p></div><div className="flex gap-2"><button className="tx-tab" onClick={squareOff} disabled={!position}>Square Off</button></div></div>
 <div className="grid xl:grid-cols-[1fr_1fr_1.2fr] gap-4 mt-4"><div className="rounded-xl border border-blue-900/30 bg-[#020b20] p-4"><div className="text-[10px] text-slate-600">PAPER CASH</div><div className="text-2xl font-black mt-1">$ {money(portfolio?.cash_balance||0)}</div><div className="text-xs text-slate-500 mt-3">Equity <b className="text-cyan-300">$ {money(equity)}</b></div><div className="text-xs text-slate-500 mt-1">Unrealized <b className={unrealized>=0?"text-emerald-300":"text-red-300"}>$ {money(unrealized)}</b></div></div>
 <div className="rounded-xl border border-purple-500/20 bg-[#09041a] p-4"><div className="text-[10px] text-slate-600">{symbol} POSITION</div><div className="text-2xl font-black mt-1">{position?.quantity?.toFixed(8)||"0"}</div><div className="text-xs text-slate-500 mt-3">Exposure <b className="text-purple-300">{exposure.toFixed(2)}%</b></div><div className="text-xs text-slate-500 mt-1">Avg <b className="text-cyan-300">$ {money(position?.average_price||0)}</b></div></div>
 <div className="rounded-xl border border-cyan-500/20 bg-[#02121b] p-4"><div className="flex gap-2 mb-3">{(["BUY","SELL"] as const).map(x=><button key={x} onClick={()=>setSide(x)} className={"tx-tab "+(side===x?"tx-tab-active":"")}>{x}</button>)}</div><div className="grid grid-cols-2 gap-2"><input type="number" min="0.000001" step="any" className="tx-input" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantity"/><div className="tx-input text-cyan-300">Live $ {money(price)}</div></div><div className="grid grid-cols-2 gap-2 mt-2"><input type="number" step="any" className="tx-input" value={stop} onChange={e=>setStop(e.target.value)} placeholder="Stop-loss $"/><input type="number" step="any" className="tx-input" value={take} onChange={e=>setTake(e.target.value)} placeholder="Take-profit $"/></div>{rr>0&&<div className="text-[11px] text-slate-500 mt-2">Risk/Reward <b className="text-cyan-300">1:{rr.toFixed(2)}</b></div>}<button onClick={submit} disabled={busy} className="btn-primary w-full mt-3">{busy?"EXECUTING...":side+" "+symbol}</button>{msg&&<div className="text-xs text-red-300 mt-2">{msg}</div>}</div></div>
 <div className="mt-5"><div className="text-xs uppercase tracking-wider text-slate-500 mb-2">Persistent Crypto Portfolio</div>{portfolio?.positions.length?<div className="grid md:grid-cols-3 gap-2">{portfolio.positions.map(p=><div className="tx-crypto-asset" key={p.symbol}><div className="flex justify-between"><span>{p.symbol}</span><b>{p.quantity.toFixed(8)}</b></div><small>Avg $ {money(p.average_price)} · Live $ {money(p.current_price||0)} · P&L $ {money(p.unrealized_pnl)}</small><div className="text-[10px] mt-1 text-slate-500">SL {p.stop_price?money(p.stop_price):"—"} · TP {p.take_price?money(p.take_price):"—"}</div></div>)}</div>:<div className="text-xs text-slate-600 p-4 border border-blue-900/20 rounded-xl">No crypto positions yet.</div>}</div>
 <div className="mt-5"><div className="text-xs uppercase tracking-wider text-slate-500 mb-2">Persistent Order Journal</div><div className="space-y-1">{trades.slice(0,8).map(t=><div key={t.id} className="flex justify-between text-xs p-2 rounded bg-blue-900/10"><span className={t.side==="BUY"?"text-emerald-300":"text-red-300"}>{t.side} {t.symbol}</span><span>{t.quantity} @ $ {money(t.price)}</span></div>)}</div></div></section>
}