"use client"
import {useEffect,useState} from "react"
import api from "@/lib/api"
const coins=["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT"]
export default function CryptoBotPanel(){const[s,setS]=useState<any>(null),[symbol,setSymbol]=useState("BTCUSDT"),[enabled,setEnabled]=useState(false),[risk,setRisk]=useState("1"),[max,setMax]=useState("25"),[running,setRunning]=useState(false),[msg,setMsg]=useState("")
const load=async()=>{try{const x=await api.get<any>("/crypto-paper-bot/status");setS(x);setSymbol(x.symbol);setEnabled(x.enabled);setRisk(String(x.risk_per_trade));setMax(String(x.max_position_pct))}catch(e){setMsg(e instanceof Error?e.message:"Bot unavailable")}}
useEffect(()=>{void load();const id=window.setInterval(load,15000);return()=>window.clearInterval(id)},[])
const configure=async(e:boolean)=>{try{const x=await api.post<any>("/crypto-paper-bot/configure?"+new URLSearchParams({symbol,enabled:String(e),risk_per_trade:risk,max_position_pct:max}).toString(),{});setS(x);setEnabled(e);setMsg(e?"Bot armed — it remains paper-only.":"Bot stopped")}catch(err){setMsg(err instanceof Error?err.message:"Configuration failed")}}
const run=async()=>{setRunning(true);try{const x=await api.post<any>("/crypto-paper-bot/run",{});setMsg(x.action==="HOLD"?"No trade: MTF confirmation is HOLD.":x.action+" executed by MTF bot.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Bot run failed")}finally{setRunning(false)}}
return <section className="glass-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="tx-section-title">Crypto Auto Paper Bot</div><p className="text-[11px] text-slate-600">5m + 15m + 30m agreement · paper execution only · no exchange orders</p></div><span className={"tx-terminal-badge "+(enabled?"text-emerald-300":"")}>{enabled?"ARMED":"STOPPED"}</span></div><div className="grid lg:grid-cols-[1fr_1fr_1fr] gap-3 mt-4"><div><label className="text-[10px] text-slate-500">SYMBOL</label><select className="tx-input w-full mt-1" value={symbol} onChange={e=>setSymbol(e.target.value)}>{coins.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="text-[10px] text-slate-500">RISK / TRADE %</label><input className="tx-input w-full mt-1" type="number" min="0.1" max="5" step="0.1" value={risk} onChange={e=>setRisk(e.target.value)}/></div><div><label className="text-[10px] text-slate-500">MAX POSITION %</label><input className="tx-input w-full mt-1" type="number" min="1" max="25" value={max} onChange={e=>setMax(e.target.value)}/></div></div><div className="flex flex-wrap gap-2 mt-4"><button className="btn-primary" onClick={()=>void configure(!enabled)}>{enabled?"STOP BOT":"ARM PAPER BOT"}</button><button className="tx-tab" onClick={()=>void run()} disabled={running}>{running?"RUNNING MTF...":"RUN ONE MTF CYCLE"}</button></div>{s&&<div className="grid md:grid-cols-4 gap-2 mt-4">{[["Decision",s.last_decision||"—"],["Symbol",s.symbol],["Last run",s.last_run_at?new Date(s.last_run_at).toLocaleTimeString():"—"],["Rule",s.last_reason||"Waiting for first cycle"]].map(([k,v])=><div className="tx-crypto-asset" key={k}><small>{k}</small><b>{v}</b></div>)}</div>}{msg&&<div className="text-xs text-cyan-300 mt-3">{msg}</div>}</section>}
