"use client"
import {useEffect,useState} from "react"
import {Activity,BarChart3,Flame,RefreshCw,ShieldCheck,TrendingDown,TrendingUp,Volume2} from "lucide-react"
import api from "@/lib/api"
type R={symbol:string;lastPrice:number;priceChangePercent:number;quoteVolume:number}
export default function CryptoResearch(){
 const [d,setD]=useState<any>(null),[error,setError]=useState("")
 const load=async()=>{try{setD(await api.get("/crypto-market/overview"));setError("")}catch(e){setError(e instanceof Error?e.message:"Research unavailable")}}
 useEffect(()=>{void load();const id=window.setInterval(load,30000);return()=>window.clearInterval(id)},[])
 const card=(title:string,value:string,sub:string,icon:any)=><div className="tx-kpi p-4"><div className="flex justify-between"><span className="tx-kpi-label">{title}</span>{icon}</div><b className="text-xl block mt-2 text-white">{value}</b><span className="text-[10px] text-slate-600">{sub}</span></div>
 return <div className="space-y-5"><div className="flex justify-between gap-3"><div><div className="tx-terminal-badge w-fit">MARKET INTELLIGENCE</div><h1 className="text-3xl font-black mt-3">Crypto Research</h1><p className="text-sm text-slate-500 mt-1">Market breadth, liquidity, volatility and momentum intelligence — separate from trade recommendations.</p></div><button className="btn-primary text-xs" onClick={()=>void load()}><RefreshCw size={13}/> Refresh</button></div>{error&&<div className="glass-card p-4 text-red-300">{error}</div>}{d&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{card("ACTIVE PAIRS",String(d.assets),"USDT market universe",<Activity size={15} className="text-cyan-300"/>)}{card("ADVANCING",String(d.breadth.up),"pairs positive",<TrendingUp size={15} className="text-emerald-300"/>)}{card("DECLINING",String(d.breadth.down),"pairs negative",<TrendingDown size={15} className="text-red-300"/>)}{card("24H VOLUME","$ "+Number(d.volume).toLocaleString("en-US",{maximumFractionDigits:0}),"aggregated tracked volume",<Volume2 size={15} className="text-purple-300"/>)}</div><div className="grid lg:grid-cols-2 gap-5"><section className="glass-card p-5"><div className="tx-section-title"><Flame size={16}/> Momentum Leaders</div><div className="grid sm:grid-cols-2 gap-2 mt-4">{d.gainers.map((x:R)=><ResearchRow key={x.symbol} x={x} positive/>)}</div></section><section className="glass-card p-5"><div className="tx-section-title"><ShieldCheck size={16}/> Weakness Monitor</div><div className="grid sm:grid-cols-2 gap-2 mt-4">{d.losers.map((x:R)=><ResearchRow key={x.symbol} x={x}/>)}</div></section></div><section className="glass-card p-5"><div className="tx-section-title"><BarChart3 size={16}/> Breadth Regime</div><div className="mt-4 h-4 rounded-full bg-slate-900 overflow-hidden flex"><div className="bg-emerald-400/70" style={{width:(d.breadth.up/Math.max(d.assets,1))*100+"%"}}/><div className="bg-slate-700" style={{width:(d.breadth.flat/Math.max(d.assets,1))*100+"%"}}/><div className="bg-red-400/70" style={{width:(d.breadth.down/Math.max(d.assets,1))*100+"%"}}/></div><div className="grid grid-cols-3 mt-3 text-xs"><span className="text-emerald-300">UP {d.breadth.up}</span><span className="text-slate-500 text-center">FLAT {d.breadth.flat}</span><span className="text-red-300 text-right">DOWN {d.breadth.down}</span></div></section></>}</div>
}
function ResearchRow({x,positive=false}:{x:R;positive?:boolean}){return <div className="tx-crypto-asset"><div className="flex justify-between"><b>{x.symbol.replace("USDT","")}</b><b className={positive?"text-emerald-400":"text-red-400"}>{x.priceChangePercent.toFixed(2)}%</b></div><strong>$ {x.lastPrice.toLocaleString("en-US",{maximumFractionDigits:8})}</strong><small>Volume $ {x.quoteVolume.toLocaleString("en-US",{maximumFractionDigits:0})}</small></div>}
