"use client"
import {useEffect,useMemo,useState} from "react"
const KEY="titanx.crypto.paper.v1"
type Pos={symbol:string;qty:number;avg:number}
type Trade={id:number;symbol:string;side:"BUY"|"SELL";qty:number;price:number;time:string}
type State={cash:number;positions:Pos[];trades:Trade[]}
const initial:State={cash:100000,positions:[],trades:[]}
const money=(n:number)=>n.toLocaleString("en-US",{maximumFractionDigits:2})
export default function CryptoPaperTerminal({symbol}:{symbol:string}){const[state,setState]=useState<State>(initial),[price,setPrice]=useState(0),[qty,setQty]=useState("0.01"),[side,setSide]=useState<"BUY"|"SELL">("BUY"),[msg,setMsg]=useState("")
useEffect(()=>{try{const s=localStorage.getItem(KEY);if(s)setState(JSON.parse(s))}catch{}},[])
useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(state))},[state])
useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch("https://api.binance.com/api/v3/ticker/price?symbol="+symbol,{cache:"no-store"});const j=await r.json();if(alive)setPrice(Number(j.price))}catch{}};void load();const id=window.setInterval(load,15000);return()=>{alive=false;window.clearInterval(id)}},[symbol])
const position=state.positions.find(p=>p.symbol===symbol),q=Math.max(0,Number(qty)||0),cost=q*price
const equity=state.cash+state.positions.reduce((s,p)=>s+p.qty*price,0),exposure=equity?((position?.qty||0)*price/equity)*100:0
const submit=()=>{if(!price||!q)return;setMsg("");setState(s=>{const ps=[...s.positions],i=ps.findIndex(p=>p.symbol===symbol);if(side==="BUY"){if(s.cash<cost){setMsg("Insufficient paper cash");return s}if(i>=0){const p=ps[i],total=p.qty+q;p.avg=(p.avg*p.qty+price*q)/total;p.qty=total}else ps.push({symbol,qty:q,avg:price});return{...s,cash:s.cash-cost,positions:ps,trades:[{id:Date.now(),symbol,side,qty:q,price,time:new Date().toISOString()},...s.trades]}}if(i<0||ps[i].qty<q){setMsg("Insufficient crypto position");return s}const p=ps[i];s.cash+=price*q;p.qty-=q;if(p.qty<=0)ps.splice(i,1);return{...s,positions:ps,trades:[{id:Date.now(),symbol,side,qty:q,price,time:new Date().toISOString()},...s.trades]}})}
const reset=()=>setState(initial)
return <section className="glass-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="tx-section-title">Crypto Paper Trading</div><p className="text-[11px] text-slate-600">Separate browser paper wallet · no exchange orders are submitted</p></div><button className="tx-tab" onClick={reset}>Reset</button></div><div className="grid xl:grid-cols-[1fr_1fr_1.2fr] gap-4 mt-4"><div className="rounded-xl border border-blue-900/30 bg-[#020b20] p-4"><div className="text-[10px] text-slate-600">PAPER CASH</div><div className="text-2xl font-black mt-1">$ {money(state.cash)}</div><div className="text-xs text-slate-500 mt-3">Equity <b className="text-cyan-300">$ {money(equity)}</b></div></div><div className="rounded-xl border border-purple-500/20 bg-[#09041a] p-4"><div className="text-[10px] text-slate-600">{symbol} POSITION</div><div className="text-2xl font-black mt-1">{position?.qty?.toFixed(6)||"0"}</div><div className="text-xs text-slate-500 mt-3">Exposure <b className="text-purple-300">{exposure.toFixed(2)}%</b></div></div><div className="rounded-xl border border-cyan-500/20 bg-[#02121b] p-4"><div className="flex gap-2 mb-3">{(["BUY","SELL"] as const).map(x=><button key={x} onClick={()=>setSide(x)} className={"tx-tab "+(side===x?"tx-tab-active":"")}>{x}</button>)}</div><div className="grid grid-cols-2 gap-2"><input className="tx-input" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantity"/><div className="tx-input text-cyan-300">Live $ {money(price)}</div></div><button onClick={submit} className="btn-primary w-full mt-3">{side} {symbol}</button>{msg&&<div className="text-xs text-red-300 mt-2">{msg}</div>}</div></div><div className="mt-5"><div className="text-xs uppercase tracking-wider text-slate-500 mb-2">Crypto Portfolio</div>{state.positions.length?<div className="grid md:grid-cols-3 gap-2">{state.positions.map(p=><div className="tx-crypto-asset" key={p.symbol}><div className="flex justify-between"><span>{p.symbol}</span><b>{p.qty.toFixed(6)}</b></div><small>Avg $ {money(p.avg)}</small></div>)}</div>:<div className="text-xs text-slate-600 p-4 border border-blue-900/20 rounded-xl">No crypto positions yet.</div>}</div><div className="mt-5"><div className="text-xs uppercase tracking-wider text-slate-500 mb-2">Order History</div><div className="space-y-1">{state.trades.slice(0,8).map(t=><div key={t.id} className="flex justify-between text-xs p-2 rounded bg-blue-900/10"><span className={t.side==="BUY"?"text-emerald-300":"text-red-300"}>{t.side} {t.symbol}</span><span>{t.qty} @ $ {money(t.price)}</span></div>)}</div></div></section>}
