"use client"

import Link from "next/link"
import { useState } from "react"
import { useAuth } from "@/contexts/AuthContext"
import MarketTicker, { usePublicMarket } from "@/components/landing/MarketTicker"
import MarketBattle from "@/components/landing/MarketBattle"
import { ArrowRight, Activity, BarChart3, Brain, ChevronRight, Cpu, Database, Globe, Lock, Menu, Network, Play, Radar, Server, Shield, Sparkles, Target, TrendingUp, Users, X, Zap } from "lucide-react"

const features = [
  { icon: Brain, title: "AI Intelligence", value: "MULTI-MODEL", text: "Market-regime detection, pattern recognition, ranking and explainable intelligence.", visual: "brain" },
  { icon: BarChart3, title: "Advanced Analytics", value: "150+ INDICATORS", text: "Institutional technicals, breadth, correlation, volatility and market-structure analytics.", visual: "bars" },
  { icon: Globe, title: "Global Indices", value: "20+ LIVE", text: "One index intelligence layer across India, US, Europe and Asia-Pacific markets.", visual: "globe" },
  { icon: Cpu, title: "Automated Trading", value: "SMART ROUTING", text: "Signal validation, risk controls, order orchestration and execution workflows.", visual: "bot" },
  { icon: Shield, title: "Risk Engine", value: "24 / 7", text: "Exposure, drawdown, concentration, volatility and circuit-breaker monitoring.", visual: "shield" },
  { icon: Server, title: "HFT Infrastructure", value: "LOW LATENCY", text: "Event-driven pipelines, WebSockets, Redis and time-series infrastructure built for scale.", visual: "server" },
]

const globalIndices = [
  ["NIFTY 50", "India", "Asia", "🇮🇳"], ["SENSEX", "India", "Asia", "🇮🇳"], ["S&P 500", "United States", "Americas", "🇺🇸"], ["NASDAQ COMPOSITE", "United States", "Americas", "🇺🇸"],
  ["DOW JONES", "United States", "Americas", "🇺🇸"], ["FTSE 100", "United Kingdom", "Europe", "🇬🇧"], ["DAX", "Germany", "Europe", "🇩🇪"], ["CAC 40", "France", "Europe", "🇫🇷"],
  ["NIKKEI 225", "Japan", "Asia", "🇯🇵"], ["HANG SENG", "Hong Kong", "Asia", "🇭🇰"], ["SHANGHAI COMPOSITE", "China", "Asia", "🇨🇳"], ["KOSPI", "South Korea", "Asia", "🇰🇷"],
]
const sectors = [["BANK NIFTY", "Financials", "bank"], ["NIFTY IT", "Technology", "tech"], ["NIFTY AUTO", "Automotive", "auto"], ["NIFTY PHARMA", "Healthcare", "pharma"], ["NIFTY FMCG", "Consumer", "fmcg"], ["NIFTY METAL", "Materials", "metal"], ["NIFTY ENERGY", "Energy", "energy"], ["NIFTY REALTY", "Real Estate", "realty"]]

function FeatureVisual({ type }: { type: string }) {
  if (type === "bars") return <div className="fx-bars">{[42,70,52,88,64,96].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div>
  if (type === "globe") return <div className="fx-globe"><Globe size={58}/><span/><span/><span/></div>
  if (type === "bot") return <div className="fx-bot"><Cpu size={48}/><i/><i/><i/></div>
  if (type === "shield") return <div className="fx-shield"><Shield size={58}/><span>RISK</span></div>
  if (type === "server") return <div className="fx-server"><Server size={58}/><span/><span/><span/></div>
  return <div className="fx-brain"><Network size={60}/><span/><span/><span/><span/></div>
}

function formatIndex(m: { price: number | null; change_pct: number | null }) {
  const price = m.price == null ? "—" : m.price.toLocaleString("en-IN", { maximumFractionDigits: 2 })
  const change = m.change_pct == null ? "FEED" : `${m.change_pct >= 0 ? "▲" : "▼"} ${Math.abs(m.change_pct).toFixed(2)}%`
  return { price, change, up: (m.change_pct ?? 0) >= 0 }
}

function WorldMarkets() {
  const { markets } = usePublicMarket()
  const find = (name: string) => markets.find(m => m.name.toUpperCase() === name.toUpperCase() || m.name.toUpperCase().includes(name.toUpperCase()))
  return <section id="markets" className="titan-section titan-world"><div className="titan-wrap">
    <div className="titan-section-head"><div><div className="titan-kicker"><Globe size={13}/> GLOBAL INDEX INTELLIGENCE</div><h2>One World. Every Major Index.</h2><p>Current index levels and daily movement from the TITAN X market engine. No individual stocks, crypto, FX, gold or commodities in this view.</p></div><div className="titan-live-badge"><i/> LIVE INDEX ENGINE</div></div>
    <div className="world-grid"><div className="world-map-card"><div className="world-map-title">GLOBAL INDEX NETWORK <span>REGION / LIVE FEED</span></div><div className="world-map-svg"><div className="continent c1"/><div className="continent c2"/><div className="continent c3"/><div className="continent c4"/><div className="continent c5"/>{[[24,43],[31,50],[48,39],[52,55],[67,45],[74,55],[82,39]].map(([x,y],i)=><b key={i} style={{left:`${x}%`,top:`${y}%`}}/>)}<div className="route r1"/><div className="route r2"/><div className="route r3"/></div><div className="map-foot"><span><i/> ASIA</span><span><i/> EUROPE</span><span><i/> AMERICAS</span><span><i/> CROSS-MARKET</span></div></div>
      <div className="exchange-card"><div className="panel-head">GLOBAL INDICES <small>CURRENT / CHANGE</small></div>{globalIndices.map(([name,country,region,flag])=>{const live=find(name); const f=live?formatIndex(live):{price:"—",change:"FEED",up:true}; return <div className="exchange-row" key={name}><span className="exchange-name"><b>{flag}</b><strong>{name}</strong><small>{country}</small></span><span className="exchange-region">{region}</span><span className="exchange-price">{f.price}</span><span className={`exchange-live ${f.up?"is-up":"is-down"}`}>{f.change}</span></div>})}</div></div>
  </div></section>
}

function SectorWall() {
  const { markets } = usePublicMarket()
  const find = (name: string) => markets.find(m => m.name.toUpperCase().includes(name.toUpperCase()))
  return <section className="titan-section titan-sector"><div className="titan-wrap"><div className="titan-section-head"><div><div className="titan-kicker"><Radar size={13}/> SECTOR INDEX INTELLIGENCE</div><h2>India's Sector Pulse</h2><p>Sector cards now show real index values when the live feed supplies them; unavailable feeds stay clearly marked.</p></div><Link href="/dashboard" className="titan-outline-btn">Open Sector Matrix <ArrowRight size={15}/></Link></div><div className="sector-grid">{sectors.map(([name,label,type],i)=>{const m=find(name); const f=m?formatIndex(m):{price:"—",change:"FEED",up:true}; return <div className="sector-card" key={name}><div className={`sector-orb ${type}`}><span/></div><div className="sector-meta"><strong>{name}</strong><small>{label}</small></div><div className="sector-spark">{[30,42,36,62,48,76,68,90].map((h,j)=><i key={j} style={{height:`${h + (i%3)*3}%`}}/>)}</div><div className="sector-signal"><span>{f.price} · {f.change}</span><b>{m?"LIVE":"FEED"}</b></div><ChevronRight size={16}/></div>})}</div></div></section>
}

export default function LandingPage() {
  const { isAuthenticated } = useAuth(); const [mobileMenuOpen,setMobileMenuOpen] = useState(false)
  const { markets, score, regime } = usePublicMarket()
  const nifty = markets.find(m=>m.name.toUpperCase().includes("NIFTY 50"))
  const niftyDisplay = nifty ? formatIndex(nifty) : {price:"—",change:"FEED",up:true}
  const liveCount = markets.filter(m=>m.price != null).length
  const regimeLabel = regime?.toUpperCase().includes("BEAR") ? "BEAR MARKET" : regime?.toUpperCase().includes("BULL") ? "BULL MARKET" : "MARKET INTELLIGENCE"
  return <main className="titan-site">
    <nav className="titan-nav"><div className="titan-wrap titan-nav-inner"><Link href="/" className="titan-brand titan-brand-logo"><img src="/titan-x-logo.svg" alt="TITAN X"/><span className="sr-only">TITAN X</span></Link><div className="titan-nav-links"><a href="#home">Home</a><a href="#markets">Markets</a><a href="#ai">AI Intelligence</a><a href="#trading">Trading</a><a href="#analytics">Analytics</a><a href="#risk">Risk Engine</a><a href="#products">Products</a><a href="#api">API</a><a href="#about">About</a></div><div className="titan-nav-actions"><button className="icon-btn" aria-label="Theme">◐</button><button className="icon-btn" aria-label="Search">⌕</button>{isAuthenticated?<Link href="/dashboard" className="nav-login">Platform</Link>:<Link href="/login" className="nav-login">Login</Link>}<Link href={isAuthenticated?"/dashboard":"/register"} className="nav-start">Get Started <ArrowRight size={14}/></Link></div><button className="mobile-menu" aria-label="Menu" onClick={()=>setMobileMenuOpen(v=>!v)}>{mobileMenuOpen?<X/>:<Menu/>}</button></div>{mobileMenuOpen&&<div className="mobile-links">{[['Home','home'],['Markets','markets'],['AI Intelligence','ai'],['Trading','trading'],['Analytics','analytics'],['Risk Engine','risk'],['Products','products'],['API','api'],['About','about']].map(([x,id])=><a key={id} href={`#${id}`} onClick={()=>setMobileMenuOpen(false)}>{x}</a>)}<Link href="/register" className="nav-start">Get Started <ArrowRight size={14}/></Link></div>}</nav>
    <div className="titan-ticker-wrap"><MarketTicker /></div>
    <section id="home" className="titan-hero"><div className="titan-hero-grid"/><div className="titan-hero-glow g1"/><div className="titan-hero-glow g2"/><div className="titan-wrap titan-hero-layout"><div className="hero-copy"><div className="titan-kicker"><Sparkles size={13}/> AI-POWERED FINANCIAL INTELLIGENCE</div><h1>The Future<br/>Trades <span>Smarter</span></h1><p>Real-time market intelligence, AI-driven analytics and automated trading infrastructure for global markets.</p><div className="hero-workflow"><span><Target/>Predict<small>Market Moves</small></span><span><Brain/>Analyze<small>Deep Insights</small></span><span><Zap/>Automate<small>Smart Execution</small></span><span><TrendingUp/>Execute<small>Optimal Results</small></span></div><div className="hero-actions"><Link href="/register" className="nav-start big">Start Trading Now <ArrowRight size={16}/></Link><Link href="/dashboard" className="titan-outline-btn"><Play size={14}/> Explore Platform</Link></div><div className="hero-trust"><span><Lock size={12}/> Secure infrastructure</span><span><Shield size={12}/> Real-time risk controls</span><span><Activity size={12}/> {liveCount} live index feeds</span></div></div><div className="hero-battle"><MarketBattle/></div></div><div className="hero-regime-strip"><span><i/> MARKET STATUS</span><strong>{regimeLabel}</strong><b>AI SCORE {typeof score === "number"?Math.round(score):"—"}</b></div></section>
    <div className="titan-capabilities"><div className="titan-wrap"><span><i/> LIVE INDICES</span><span>GLOBAL INDEX INTELLIGENCE</span><span>AI SIGNALS</span><span>SECTOR PULSE</span><span>PORTFOLIO RISK</span><span>AUTOMATED EXECUTION</span><span>LOW-LATENCY INFRA</span></div></div>
    <section id="ai" className="titan-section"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker">ONE INTELLIGENCE LAYER</div><h2>Everything an Investment Desk Needs</h2><p>High-density financial intelligence with the visual language of an institutional command center.</p></div></div><div className="feature-grid">{features.map(f=>{const Icon=f.icon;return <div className="feature-card" key={f.title}><div className="feature-visual"><FeatureVisual type={f.visual}/></div><div className="feature-body"><div className="feature-title"><Icon size={17}/><strong>{f.title}</strong></div><p>{f.text}</p><div className="feature-bottom"><b>{f.value}</b><ChevronRight size={17}/></div></div></div>})}</div></div></section>
    <WorldMarkets/><SectorWall/>
    <section id="analytics" className="titan-section titan-command"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker"><Activity size={13}/> INSTITUTIONAL COMMAND CENTER</div><h2>See the Market Before the Market Moves</h2><p>Live index state, regime intelligence and execution workflow in one visual operating layer.</p></div></div><div className="command-grid"><div className="command-card wide"><div className="panel-head">NIFTY 50 INDEX ENGINE <span><i/> LIVE</span></div><div className="prediction-header"><div><small>CURRENT INDEX LEVEL</small><strong>{niftyDisplay.price}</strong><b className={niftyDisplay.up?"is-up":"is-down"}>{niftyDisplay.change}</b></div><div className="prediction-badge">AI REGIME<strong>{regimeLabel}</strong></div></div><div className="big-chart index-chart"><div className="chart-lines"/><svg viewBox="0 0 900 260" preserveAspectRatio="none"><polyline points="0,200 65,185 120,205 180,152 240,176 305,125 370,145 435,92 500,118 565,78 630,96 700,58 770,76 835,40 900,24"/></svg><div className="chart-glow-point p1"/><div className="chart-glow-point p2"/><div className="chart-glow-point p3"/></div><div className="signal-strip"><span>INDEX FEED <b>{nifty?.price==null?"WAITING":"CONNECTED"}</b></span><span>AI SCORE <b>{typeof score === "number"?Math.round(score):"—"}</b></span><span>REGIME <b>{regimeLabel}</b></span><span>REFRESH <b>30s</b></span></div></div><div className="command-card"><div className="panel-head">INDEX BREADTH <span>LIVE</span></div><div className="portfolio-ring"><div><strong>{markets.filter(m=>typeof m.change_pct==="number"&&m.change_pct>0).length}</strong><small>POSITIVE INDICES</small></div></div><div className="portfolio-list"><span>Positive <b>{markets.filter(m=>typeof m.change_pct==="number"&&m.change_pct>0).length}</b></span><span>Negative <b>{markets.filter(m=>typeof m.change_pct==="number"&&m.change_pct<0).length}</b></span><span>Flat <b>{markets.filter(m=>m.change_pct===0).length}</b></span><span>Live feeds <b>{liveCount}</b></span></div></div><div className="command-card"><div className="panel-head">MARKET INTELLIGENCE AI <span><i/> LIVE</span></div><div className="news-list"><div><b>01</b><p>Macro and policy signals mapped to index regime<small>REGIME ENGINE</small></p></div><div><b>02</b><p>Cross-market moves compared across regions<small>GLOBAL INDEX</small></p></div><div><b>03</b><p>Sector rotation connected to Indian indices<small>SECTOR PULSE</small></p></div><div><b>04</b><p>AI converts market state into explainable signals<small>AI CLASSIFIED</small></p></div></div></div></div></div></section>
    <section id="trading" className="titan-section titan-execution"><div className="titan-wrap"><div className="execution-layout"><div><div className="titan-kicker"><Zap size={13}/> AUTOMATED EXECUTION</div><h2>Signal → Risk → Order → Fill</h2><p>Move from AI idea to controlled execution through a transparent decision pipeline.</p><div className="execution-steps"><div><b>01</b><strong>Predict</strong><small>AI ensemble detects opportunity.</small></div><div><b>02</b><strong>Validate</strong><small>Technical, news and risk checks.</small></div><div><b>03</b><strong>Route</strong><small>Smart order orchestration.</small></div><div><b>04</b><strong>Execute</strong><small>Real-time controls and audit trail.</small></div></div></div><div className="execution-tech"><div className="exec-core"><Zap size={32}/><strong>AI<br/>EXECUTION</strong></div><div className="exec-node n1">SIGNAL</div><div className="exec-node n2">RISK</div><div className="exec-node n3">ORDER</div><div className="exec-node n4">FILL</div><div className="exec-orbit o1"/><div className="exec-orbit o2"/></div></div></div></section>
    <section id="risk" className="titan-section titan-risk"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker"><Shield size={13}/> RISK INTELLIGENCE</div><h2>Protection Designed Into Every Decision</h2><p>Portfolio risk is not a separate screen. It is part of the signal, order and execution lifecycle.</p></div></div><div className="risk-grid">{[['Portfolio Exposure','LIVE','Exposure'],['Drawdown Control','LIVE','Headroom'],['Volatility Monitor','LIVE','Normalised'],['Real-Time Alerts','24/7','Active']].map(([a,b,c],i)=><div className="risk-tech" key={a}><span>0{i+1}</span><Shield size={22}/><strong>{a}</strong><small>{c}</small><div className="risk-bar"><i style={{width:i===3?'100%':`${62+i*9}%`}}/></div><b>{b}</b></div>)}</div></div></section>
    <section id="products" className="titan-stats"><div className="titan-wrap">{[["20+","Global Indices",Globe],["30s","Market Refresh",Activity],["150+","Analytics Indicators",BarChart3],["AI","Regime Engine",Brain],["24/7","Risk Monitoring",Shield],["100%","Index-Only Market View",Radar]].map(([v,l,I])=>{const Icon=I as any;return <div key={String(l)}><Icon size={21}/><strong>{v}</strong><small>{l}</small></div>})}</div></section>
    <footer id="about" className="titan-footer"><div className="titan-wrap"><div><Link href="/" className="titan-brand titan-brand-logo"><img src="/titan-x-logo.svg" alt="TITAN X"/><span className="sr-only">TITAN X</span></Link><p>High-performance financial intelligence for modern investors, trading desks and financial technology platforms.</p></div><div className="footer-links"><span>PLATFORM</span><a href="#markets">Markets</a><a href="#ai">AI Intelligence</a><a href="#trading">Trading</a><a href="#analytics">Analytics</a><a href="#risk">Risk Engine</a></div><div id="api" className="footer-links"><span>CONNECT</span><Link href="/dashboard">Platform</Link><Link href="/login">Login</Link><Link href="/register">Get Started</Link><a href="#home">Back to top ↑</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} TITAN X. All rights reserved.</span><span>LIVE INDEX DATA • AI • EXECUTION • RISK</span></div></footer>
  </main>
}
