"use client"

import Link from "next/link"
import { useState } from "react"
import { useAuth } from "@/contexts/AuthContext"
import MarketTicker, { usePublicMarket } from "@/components/landing/MarketTicker"
import MarketBattle from "@/components/landing/MarketBattle"
import { ArrowRight, Activity, BarChart3, Brain, ChevronRight, Cpu, Database, Globe, Lock, Menu, Network, Play, Radar, Server, Shield, Sparkles, Target, TrendingUp, Users, X, Zap } from "lucide-react"

const features = [
  { icon: Brain, title: "AI Intelligence", value: "MULTI-MODEL", text: "Deep-learning market regime detection, pattern recognition, ranking and explainable signals.", visual: "brain" },
  { icon: BarChart3, title: "Advanced Analytics", value: "150+ INDICATORS", text: "Institutional charts, technicals, breadth, correlation, volatility and market structure.", visual: "bars" },
  { icon: Globe, title: "Global Markets", value: "60+ EXCHANGES", text: "One intelligence layer across equities, indices, commodities, FX and digital assets.", visual: "globe" },
  { icon: Cpu, title: "Automated Trading", value: "SMART ROUTING", text: "Signal validation, risk controls, order orchestration and execution workflows.", visual: "bot" },
  { icon: Shield, title: "Risk Engine", value: "24 / 7", text: "Exposure, drawdown, concentration, volatility and circuit-breaker monitoring.", visual: "shield" },
  { icon: Server, title: "HFT Infrastructure", value: "LOW LATENCY", text: "Event-driven pipelines, WebSockets, Redis and time-series infrastructure built for scale.", visual: "server" },
]

const globalExchanges = [["NSE","India","Asia","🇮🇳"],["BSE","India","Asia","🇮🇳"],["NASDAQ","United States","Americas","🇺🇸"],["NYSE","United States","Americas","🇺🇸"],["LSE","United Kingdom","Europe","🇬🇧"],["JPX","Japan","Asia","🇯🇵"],["HKEX","Hong Kong","Asia","🇭🇰"],["SSE","China","Asia","🇨🇳"]]
const sectors = [["NIFTY BANK","Financials","bank"],["NIFTY IT","Technology","tech"],["NIFTY AUTO","Automotive","auto"],["NIFTY PHARMA","Healthcare","pharma"],["NIFTY FMCG","Consumer","fmcg"],["NIFTY METAL","Materials","metal"],["NIFTY ENERGY","Energy","energy"],["NIFTY REALTY","Real Estate","realty"]]

function FeatureVisual({ type }: { type: string }) {
  if (type === "bars") return <div className="fx-bars">{[42,70,52,88,64,96].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div>
  if (type === "globe") return <div className="fx-globe"><Globe size={58}/><span/><span/><span/></div>
  if (type === "bot") return <div className="fx-bot"><Cpu size={48}/><i/><i/><i/></div>
  if (type === "shield") return <div className="fx-shield"><Shield size={58}/><span>RISK</span></div>
  if (type === "server") return <div className="fx-server"><Server size={58}/><span/><span/><span/></div>
  return <div className="fx-brain"><Network size={60}/><span/><span/><span/><span/></div>
}

function WorldMarkets() {
  const { markets } = usePublicMarket()
  const find = (names: string[]) => markets.find(m => names.some(n => m.name.toUpperCase().includes(n)))
  return <section id="markets" className="titan-section titan-world"><div className="titan-wrap">
    <div className="titan-section-head"><div><div className="titan-kicker"><Globe size={13}/> GLOBAL MARKET INTELLIGENCE</div><h2>One World. Every Market.</h2><p>Monitor exchanges, indices and cross-market signals through a single high-density intelligence layer.</p></div><div className="titan-live-badge"><i/> LIVE MARKET ENGINE</div></div>
    <div className="world-grid"><div className="world-map-card"><div className="world-map-title">GLOBAL EXCHANGE NETWORK <span>60+ VENUES</span></div><div className="world-map-svg"><div className="continent c1"/><div className="continent c2"/><div className="continent c3"/><div className="continent c4"/><div className="continent c5"/>{[[24,43],[31,50],[48,39],[52,55],[67,45],[74,55],[82,39]].map(([x,y],i)=><b key={i} style={{left:`${x}%`,top:`${y}%`}}/>)}<div className="route r1"/><div className="route r2"/><div className="route r3"/></div><div className="map-foot"><span><i/> ASIA</span><span><i/> EUROPE</span><span><i/> AMERICAS</span><span><i/> MIDDLE EAST</span></div></div>
      <div className="exchange-card"><div className="panel-head">WORLD EXCHANGES <small>STATUS / REGION</small></div>{globalExchanges.map(([name,country,region,flag])=>{const live=find([name]);return <div className="exchange-row" key={name}><span className="exchange-name"><b>{flag}</b><strong>{name}</strong><small>{country}</small></span><span className="exchange-region">{region}</span><span className="exchange-price">{live?.price == null ? "—" : live.price.toLocaleString("en-IN",{maximumFractionDigits:2})}</span><span className="exchange-live"><i/> {live ? "LIVE" : "FEED"}</span></div>})}</div></div>
  </div></section>
}

function SectorWall() { return <section className="titan-section titan-sector"><div className="titan-wrap"><div className="titan-section-head"><div><div className="titan-kicker"><Radar size={13}/> SECTOR INTELLIGENCE</div><h2>Market Sectors Under the AI Lens</h2><p>See sector rotation, momentum and relative strength as an intelligence layer—not just a chart.</p></div><Link href="/dashboard" className="titan-outline-btn">Open Sector Matrix <ArrowRight size={15}/></Link></div><div className="sector-grid">{sectors.map(([name,label,type],i)=><div className="sector-card" key={name}><div className={`sector-orb ${type}`}><span/></div><div className="sector-meta"><strong>{name}</strong><small>{label}</small></div><div className="sector-spark">{[30,42,36,62,48,76,68,90].map((h,j)=><i key={j} style={{height:`${h + (i%3)*3}%`}}/>)}</div><div className="sector-signal"><span>AI RELATIVE STRENGTH</span><b>{i%2===0?"WATCH":"TRACK"}</b></div><ChevronRight size={16}/></div>)}</div></div></section> }

export default function LandingPage() {
  const { isAuthenticated } = useAuth(); const [mobileMenuOpen,setMobileMenuOpen] = useState(false)
  return <main className="titan-site">
    <nav className="titan-nav"><div className="titan-wrap titan-nav-inner"><Link href="/" className="titan-brand"><span className="titan-brand-mark">X</span><span><strong>TITAN <em>X</em></strong><small>AI · DATA · SPEED · PRECISION</small></span></Link><div className="titan-nav-links"><a href="#home">Home</a><a href="#markets">Markets</a><a href="#ai">AI Intelligence</a><a href="#trading">Trading</a><a href="#analytics">Analytics</a><a href="#risk">Risk Engine</a><a href="#products">Products</a><a href="#api">API</a><a href="#about">About</a></div><div className="titan-nav-actions"><button className="icon-btn">◐</button><button className="icon-btn">⌕</button>{isAuthenticated?<Link href="/dashboard" className="nav-login">Platform</Link>:<Link href="/login" className="nav-login">Login</Link>}<Link href={isAuthenticated?"/dashboard":"/register"} className="nav-start">Get Started <ArrowRight size={14}/></Link></div><button className="mobile-menu" onClick={()=>setMobileMenuOpen(v=>!v)}>{mobileMenuOpen?<X/>:<Menu/>}</button></div>{mobileMenuOpen&&<div className="mobile-links">{['Home','Markets','AI Intelligence','Trading','Analytics','Risk Engine','Products','API','About'].map(x=><a key={x} href={`#${x.toLowerCase().replaceAll(' ','-')}`} onClick={()=>setMobileMenuOpen(false)}>{x}</a>)}<Link href="/register" className="nav-start">Get Started <ArrowRight size={14}/></Link></div>}</nav>
    <div className="titan-ticker-wrap"><MarketTicker /></div>
    <section id="home" className="titan-hero"><div className="titan-hero-grid"/><div className="titan-hero-glow g1"/><div className="titan-hero-glow g2"/><div className="titan-wrap titan-hero-layout"><div className="hero-copy"><div className="titan-kicker"><Sparkles size={13}/> AI-POWERED FINANCIAL INTELLIGENCE</div><h1>The Future<br/>Trades <span>Smarter</span></h1><p>Real-time market intelligence, AI-driven analytics and automated trading infrastructure for global markets.</p><div className="hero-workflow"><span><Target/>Predict<small>Market Moves</small></span><span><Brain/>Analyze<small>Deep Insights</small></span><span><Zap/>Automate<small>Smart Execution</small></span><span><TrendingUp/>Execute<small>Optimal Results</small></span></div><div className="hero-actions"><Link href="/register" className="nav-start big">Start Trading Now <ArrowRight size={16}/></Link><Link href="/dashboard" className="titan-outline-btn"><Play size={14}/> Watch Platform Tour</Link></div><div className="hero-trust"><span><Lock size={12}/> Secure infrastructure</span><span><Shield size={12}/> Real-time risk controls</span><span><Activity size={12}/> Live market engine</span></div></div><div className="hero-battle"><MarketBattle/></div></div></section>
    <div className="titan-capabilities"><div className="titan-wrap"><span><i/> LIVE MARKET DATA</span><span>GLOBAL EQUITIES</span><span>INDEX INTELLIGENCE</span><span>AI SIGNALS</span><span>PORTFOLIO RISK</span><span>AUTOMATED EXECUTION</span><span>LOW-LATENCY INFRA</span></div></div>
    <section id="ai" className="titan-section"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker">ONE INTELLIGENCE LAYER</div><h2>Everything an Investment Desk Needs</h2><p>High-density financial intelligence with the visual language of an institutional command center.</p></div></div><div className="feature-grid">{features.map(f=>{const Icon=f.icon;return <div className="feature-card" key={f.title}><div className="feature-visual"><FeatureVisual type={f.visual}/></div><div className="feature-body"><div className="feature-title"><Icon size={17}/><strong>{f.title}</strong></div><p>{f.text}</p><div className="feature-bottom"><b>{f.value}</b><ChevronRight size={17}/></div></div></div>})}</div></div></section>
    <WorldMarkets/><SectorWall/>
    <section id="analytics" className="titan-section titan-command"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker"><Activity size={13}/> INSTITUTIONAL COMMAND CENTER</div><h2>See the Market Before the Market Moves</h2><p>AI prediction, portfolio intelligence, market news and execution signals in one visual operating layer.</p></div></div><div className="command-grid"><div className="command-card wide"><div className="panel-head">AI PREDICTION ENGINE <span><i/> LIVE</span></div><div className="prediction-header"><div><small>NIFTY 50 · 15 MIN TIMEFRAME</small><strong>24,823.15</strong><b>+0.68%</b></div><div className="prediction-badge">PREDICTED MOVE<strong>+1.32%</strong></div></div><div className="big-chart"><div className="chart-lines"/><svg viewBox="0 0 900 260" preserveAspectRatio="none"><polyline points="0,215 55,188 95,205 145,150 205,175 260,112 310,142 370,92 425,122 475,70 520,96 580,52 635,83 690,40 750,62 820,26 900,10"/></svg><div className="chart-glow-point p1"/><div className="chart-glow-point p2"/><div className="chart-glow-point p3"/></div><div className="signal-strip"><span>AI SIGNAL <b>BUY</b></span><span>CONFIDENCE <b>87%</b></span><span>TARGET <b>25,150</b></span><span>STOP LOSS <b>24,250</b></span></div></div><div className="command-card"><div className="panel-head">PORTFOLIO OVERVIEW <span>LIVE</span></div><div className="portfolio-ring"><div><strong>₹12.8L</strong><small>TOTAL VALUE</small></div></div><div className="portfolio-list"><span>Equity <b>52%</b></span><span>F&amp;O <b>24%</b></span><span>Options <b>12%</b></span><span>Crypto <b>8%</b></span><span>Others <b>4%</b></span></div></div><div className="command-card"><div className="panel-head">MARKET NEWS AI <span><i/> LIVE</span></div><div className="news-list"><div><b>01</b><p>Macro and policy signals classified in real time<small>HIGH IMPACT</small></p></div><div><b>02</b><p>Company news mapped to sector momentum<small>POSITIVE</small></p></div><div><b>03</b><p>Global risk events linked to Indian markets<small>MARKET IMPACT</small></p></div><div><b>04</b><p>AI extracts signal from high-volume news flow<small>AI CLASSIFIED</small></p></div></div></div></div></div></section>
    <section id="trading" className="titan-section titan-execution"><div className="titan-wrap"><div className="execution-layout"><div><div className="titan-kicker"><Zap size={13}/> AUTOMATED EXECUTION</div><h2>Signal → Risk → Order → Fill</h2><p>Move from AI idea to controlled execution through a transparent decision pipeline.</p><div className="execution-steps"><div><b>01</b><strong>Predict</strong><small>AI ensemble detects opportunity.</small></div><div><b>02</b><strong>Validate</strong><small>Technical, news and risk checks.</small></div><div><b>03</b><strong>Route</strong><small>Smart order orchestration.</small></div><div><b>04</b><strong>Execute</strong><small>Real-time controls and audit trail.</small></div></div></div><div className="execution-tech"><div className="exec-core"><Zap size={32}/><strong>AI<br/>EXECUTION</strong></div><div className="exec-node n1">SIGNAL</div><div className="exec-node n2">RISK</div><div className="exec-node n3">ORDER</div><div className="exec-node n4">FILL</div><div className="exec-orbit o1"/><div className="exec-orbit o2"/></div></div></div></section>
    <section id="risk" className="titan-section titan-risk"><div className="titan-wrap"><div className="titan-section-head center"><div><div className="titan-kicker"><Shield size={13}/> RISK INTELLIGENCE</div><h2>Protection Designed Into Every Decision</h2><p>Portfolio risk is not a separate screen. It is part of the signal, order and execution lifecycle.</p></div></div><div className="risk-grid">{[['Portfolio Exposure','62%','Exposure'],['Drawdown Control','18%','Headroom'],['Volatility Monitor','74%','Normalised'],['Real-Time Alerts','24/7','Active']].map(([a,b,c],i)=><div className="risk-tech" key={a}><span>0{i+1}</span><Shield size={22}/><strong>{a}</strong><small>{c}</small><div className="risk-bar"><i style={{width:i===3?'100%':`${62+i*9}%`}}/></div><b>{b}</b></div>)}</div></div></section>
    <section id="products" className="titan-stats"><div className="titan-wrap">{[["<1ms","Target Processing",Zap],["99.98%","Availability",Activity],["50TB+","Daily Data Layer",Database],["1M+","AI Predictions / Day",Brain],["60+","Stock Exchanges",Globe],["100K+","Active Users",Users]].map(([v,l,I])=>{const Icon=I as any;return <div key={String(l)}><Icon size={21}/><strong>{v}</strong><small>{l}</small></div>})}</div></section>
    <footer id="about" className="titan-footer"><div className="titan-wrap"><div><div className="titan-brand"><span className="titan-brand-mark">X</span><span><strong>TITAN <em>X</em></strong><small>AI · DATA · SPEED · PRECISION</small></span></div><p>High-performance financial intelligence for modern investors, trading desks and financial technology platforms.</p></div><div className="footer-links"><span>PLATFORM</span><a href="#markets">Markets</a><a href="#ai">AI Intelligence</a><a href="#trading">Trading</a><a href="#analytics">Analytics</a><a href="#risk">Risk Engine</a></div><div id="api" className="footer-links"><span>CONNECT</span><Link href="/dashboard">Platform</Link><Link href="/login">Login</Link><Link href="/register">Get Started</Link><a href="#home">Back to top ↑</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} TITAN X. All rights reserved.</span><span>MARKET DATA • AI • EXECUTION • RISK</span></div></footer>
  </main>
}
