#!/usr/bin/env python3
"""Migration helper — run, create, or revert Alembic migrations.

Usage:
    python tools/migrate.py upgrade             # Apply all pending
    python tools/migrate.py downgrade           # Revert last migration
    python tools/migrate.py downgrade <rev>     # Revert to revision
    python tools/migrate.py revision <message>  # Autogenerate new revision
    python tools/migrate.py history             # Show migration history
    python tools/migrate.py current             # Show current revision
    python tools/migrate.py check               # Check if migration is needed
"""
import subprocess
import sys

BASE = ["alembic", "-c", "alembic.ini"]


def main() -> None:
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(1)

    command = args[0]
    if command == "upgrade":
        target = args[1] if len(args) > 1 else "head"
        run("upgrade", target)
    elif command == "downgrade":
        target = args[1] if len(args) > 1 else "-1"
        run("downgrade", target)
    elif command == "revision":
        message = args[1] if len(args) > 1 else "autogenerated"
        run("revision", "--autogenerate", "-m", message)
    elif command == "history":
        run("history")
    elif command == "current":
        run("current")
    elif command == "check":
        result = subprocess.run([*BASE, "check"], capture_output=True, text=True)
        if result.returncode == 0:
            print("No new migrations needed.")
        else:
            print(result.stdout or result.stderr)
            sys.exit(result.returncode)
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)


def run(*args: str) -> None:
    cmd = [*BASE, *args]
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
